name: Testing test

on: push

jobs:
  test:
    name: Test my site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./test
        with:
          USERNAME: "david"
          PASSWORD: "pass"
          VCENTERHOST: "vcenterhost" 